-- Guarded curation schema and lossless legacy inventory (ADR-0026).
-- Payload rows in curated_revisions are immutable; workflow state lives separately.

CREATE TABLE IF NOT EXISTS curated_answers (
    id BIGSERIAL PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    author TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE curated_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_curated_id BIGINT UNIQUE,
    active_revision_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    retired_at TIMESTAMPTZ
);

CREATE TABLE curated_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL REFERENCES curated_entries(id),
    revision_number INTEGER NOT NULL CHECK (revision_number > 0),
    predecessor_revision_id BIGINT REFERENCES curated_revisions(id),
    question TEXT NOT NULL CHECK (length(btrim(question)) > 0),
    answer TEXT NOT NULL CHECK (length(btrim(answer)) > 0),
    department TEXT,
    programs JSONB NOT NULL DEFAULT '[]'::jsonb,
    evidence_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    representative_question TEXT,
    paraphrase_question TEXT,
    expected_evidence TEXT,
    change_reason TEXT NOT NULL DEFAULT '',
    linked_feedback_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    provenance_status TEXT NOT NULL CHECK (
        provenance_status IN ('needs_review', 'submitted', 'reviewed')
    ),
    content_hash TEXT NOT NULL,
    created_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entry_id, revision_number),
    UNIQUE (entry_id, content_hash),
    CHECK (jsonb_typeof(programs) = 'array'),
    CHECK (jsonb_typeof(evidence_refs) = 'array'),
    CHECK (jsonb_typeof(linked_feedback_ids) = 'array')
);

ALTER TABLE curated_entries
    ADD CONSTRAINT curated_entries_active_revision_fk
    FOREIGN KEY (active_revision_id) REFERENCES curated_revisions(id);

CREATE TABLE curation_revision_state (
    revision_id BIGINT PRIMARY KEY REFERENCES curated_revisions(id),
    state TEXT NOT NULL CHECK (
        state IN ('draft', 'validating', 'blocked', 'ready', 'publishing', 'active', 'retired')
    ),
    state_version INTEGER NOT NULL DEFAULT 1 CHECK (state_version > 0),
    reason TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE curation_validation_runs (
    id TEXT PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES curated_revisions(id),
    fingerprint TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('pending', 'running', 'passed', 'failed', 'timed_out', 'cancelled', 'stale')
    ),
    workflow_execution_id TEXT,
    error_code TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (revision_id, fingerprint)
);

CREATE TABLE curation_validation_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES curation_validation_runs(id) ON DELETE CASCADE,
    step TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('pending', 'running', 'passed', 'failed', 'timed_out', 'skipped')
    ),
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    case_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    UNIQUE (run_id, step),
    CHECK (jsonb_typeof(details) = 'object'),
    CHECK (jsonb_typeof(case_ids) = 'array')
);

CREATE TABLE curation_human_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES curated_revisions(id),
    validation_run_id TEXT NOT NULL REFERENCES curation_validation_runs(id),
    fingerprint TEXT NOT NULL,
    decision TEXT NOT NULL CHECK (
        decision IN ('confirm_no_conflict', 'valid_scoped_exception', 'reject', 'replace_outdated')
    ),
    reviewer_label TEXT NOT NULL CHECK (length(btrim(reviewer_label)) > 0),
    reason TEXT NOT NULL CHECK (length(btrim(reason)) > 0),
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE curation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT REFERENCES curated_entries(id),
    revision_id BIGINT REFERENCES curated_revisions(id),
    validation_run_id TEXT REFERENCES curation_validation_runs(id),
    event_type TEXT NOT NULL,
    actor_type TEXT NOT NULL CHECK (actor_type IN ('admin', 'worker', 'n8n', 'migration')),
    actor_label TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT '',
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (jsonb_typeof(payload) = 'object')
);

CREATE TABLE curation_jobs (
    id TEXT PRIMARY KEY,
    validation_run_id TEXT NOT NULL REFERENCES curation_validation_runs(id),
    step TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('pending', 'leased', 'succeeded', 'failed', 'timed_out', 'cancelled')
    ),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_expires_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (validation_run_id, step)
);

CREATE TABLE curation_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    aggregate_id TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (
        status IN ('pending', 'delivering', 'delivered', 'failed')
    ),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_expires_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at TIMESTAMPTZ,
    UNIQUE (event_type, aggregate_id),
    CHECK (jsonb_typeof(payload) = 'object')
);

INSERT INTO curated_entries (id, legacy_curated_id, created_at, retired_at)
SELECT id, id, created_at, CASE WHEN active THEN NULL ELSE created_at END
FROM curated_answers
ON CONFLICT (id) DO NOTHING;

INSERT INTO curated_revisions (
    entry_id, revision_number, question, answer, department, programs,
    evidence_refs, change_reason, provenance_status, content_hash,
    created_by, created_at
)
SELECT
    id, 1, question, answer, NULL, '[]'::jsonb,
    '[]'::jsonb, 'Migrated from the legacy curated_answers table.',
    'needs_review', 'legacy-md5:' || md5(question || E'\n' || answer),
    author, created_at
FROM curated_answers
ON CONFLICT (entry_id, revision_number) DO NOTHING;

INSERT INTO curation_revision_state (revision_id, state, reason, updated_at)
SELECT r.id, CASE WHEN a.active THEN 'active' ELSE 'retired' END,
       'Legacy state preserved; provenance requires review.', a.created_at
FROM curated_answers a
JOIN curated_revisions r ON r.entry_id = a.id AND r.revision_number = 1
ON CONFLICT (revision_id) DO NOTHING;

UPDATE curated_entries e
SET active_revision_id = r.id
FROM curated_answers a
JOIN curated_revisions r ON r.entry_id = a.id AND r.revision_number = 1
WHERE e.id = a.id AND e.active_revision_id IS NULL AND a.active;

INSERT INTO curation_events (
    entry_id, revision_id, event_type, actor_type, reason, payload, created_at
)
SELECT e.id, r.id, 'legacy_migrated', 'migration',
       'Legacy row preserved without fabricated scope, evidence, or approval.',
       jsonb_build_object('active', a.active, 'provenance_status', 'needs_review'),
       a.created_at
FROM curated_answers a
JOIN curated_entries e ON e.id = a.id
JOIN curated_revisions r ON r.entry_id = e.id AND r.revision_number = 1
WHERE NOT EXISTS (
    SELECT 1 FROM curation_events existing
    WHERE existing.revision_id = r.id AND existing.event_type = 'legacy_migrated'
);

SELECT setval(
    pg_get_serial_sequence('curated_entries', 'id'),
    COALESCE((SELECT max(id) FROM curated_entries), 1),
    EXISTS (SELECT 1 FROM curated_entries)
);

CREATE OR REPLACE FUNCTION reject_curated_revision_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'curated revisions are immutable; create a successor revision';
END;
$$;

CREATE TRIGGER curated_revisions_immutable
BEFORE UPDATE OR DELETE ON curated_revisions
FOR EACH ROW EXECUTE FUNCTION reject_curated_revision_update();

CREATE INDEX curation_validation_runs_revision_idx
    ON curation_validation_runs (revision_id, created_at DESC);
CREATE INDEX curation_events_revision_idx
    ON curation_events (revision_id, created_at);
CREATE INDEX curation_jobs_ready_idx
    ON curation_jobs (status, available_at);
CREATE INDEX curation_outbox_ready_idx
    ON curation_outbox (status, available_at);
